fix(agents): MessageTokenizer storage key conflict (#2143) (#2144)
Rename MessageTokenizer storage key:
"agents-features-tracing"->"agents-features-message-tokenizer"

MessageTokenizer AIAgentStorageKey named "agents-features-tracing",
causing a runtime exception when Tracing feature is also installed (they
have the same name):
```
ai.koog.agents.core.agent.GraphAIAgent - Execution exception reported by server!
java.lang.IllegalArgumentException: Feature ai.koog.agents.core.agent.entity.AIAgentStorageKey@35e21111(name=agents-features-tracing) is found, but it is not of the expected type.
Expected type: MessageTokenizer
Actual type: Tracing
        at ai.koog.agents.core.feature.pipeline.AIAgentPipelineImpl.feature(AIAgentPipelineImpl.kt:104)
```

Closes #2143

(cherry picked from commit d97a6e4dec1513e7d75bc19cfa2453199dcead2f)