Update aws sdk version
<!--
Thank you for opening a pull request!

Please add a brief description of the proposed change here.
Also, please tick the appropriate points in the checklist below.
-->

[KG-238](https://youtrack.jetbrains.com/issue/KG-238) Bedrock
ClassNotFoundException: okhttp3.ConnectionListener
This pr updates the `bedrockruntime` to be an api dependency, and
updates the version of the `bedrockruntime` to `1.5.16`, so that it
depends on a stable version of `okhttp`. Before this change, maven
project using `bedrock-client` dependency could fail in runtime.

## Motivation and Context
<!-- Why is this change needed? What problem does it solve? -->

## Breaking Changes
<!-- Will users need to update their code or configurations? -->

---

#### Type of the changes
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Documentation update
- [ ] Tests improvement
- [ ] Refactoring

#### Checklist
- [x] The pull request has a description of the proposed change
- [x] I read the [Contributing
Guidelines](https://github.com/JetBrains/koog/blob/main/CONTRIBUTING.md)
before opening the pull request
- [x] The pull request uses **`develop`** as the base branch
- [ ] Tests for the changes have been added
- [x] All new and existing tests passed

##### Additional steps for pull requests adding a new feature
- [x] An issue describing the proposed change exists
- [x] The pull request includes a link to the issue
- [ ] The change was discussed and approved in the issue
- [ ] Docs have been added / updated

Co-authored-by: Konstantin Pavlov <1517853+kpavlov@users.noreply.github.com>